
## oErrors


**initialised**: `bool` , The initialised state of the object.

### Errors.init(options, options.sentryEndpoint, options.siteVersion, options.logLevel, raven)

Initialises the Error object with a Raven dependency.

All options are optional, if a configuration option is missing, the module
will try to initialise using any configuration found in the DOM using the
meta and link tags.

**Parameters**

**options**: `Object`, Initialises the Error object with a Raven dependency.

All options are optional, if a configuration option is missing, the module
will try to initialise using any configuration found in the DOM using the
meta and link tags.

**options.sentryEndpoint**: `String`, Optional if configued via the DOM, Required if not, must be a valid [https://app.getsentry.com/docs/platforms/|Sentry DSN](https://app.getsentry.com/docs/platforms/|Sentry DSN).

**options.siteVersion**: `String`, Optional, optionally the version of the code the page is running. This tags each error with the code version

**options.logLevel**: `String`, Optional, see Logger.level for valid names

**raven**: `Object`, The Raven JS client object.

**Returns**: `Errors`

**Example**:
```js
<!-- DOM configuration settings -->
<link rel="oErrors:sentryEndpoint" href="//sentry@app.getsentry.com/appid">
<meta name="oErrors:siteVersion" content="v1.0.0">
```

### Errors.report(error, context)

Report an Error object to the error aggregator.

**Parameters**

**error**: `Error`, The error object to report.

**context**: `Object`, Optional context to attach to the Error in the
                           aggregator

**Returns**: , undefined

### Errors.error(error, context)

Report an error to the error aggregator.

**Parameters**

**error**: `Error`, The error to report

**context**: `Object`, Additional contextual information for the error.

**Returns**: `Error`, - The original 'error' argument

**Example**:
```js
// Reports a caught Error generated by the Promise
fetch('example.com').then(doSomething).catch(oErrors.error);,// Reports and re-throws the caught error
try {
  doSomething();
} catch(e) {
  throw oErrors.error(e);
}
```

**Example**:
```js
// Reports a caught Error generated by the Promise
fetch('example.com').then(doSomething).catch(oErrors.error);,// Reports and re-throws the caught error
try {
  doSomething();
} catch(e) {
  throw oErrors.error(e);
}
```

### Errors.warn(warnMessage)

Log a 'WARN' level log.  Intended to have the same semantics as
console.warn.
This stores the log in memory and will attach the last `n` log lines to the
context of the error. See [Errors#log](#errors#log) to log a log message.

**Parameters**

**warnMessage**: `String`, The message to log.

**Returns**: , undefined

### Errors.log(logMessage)

Log a 'LOG' level log.  Intended to have the same semantics as console.log.
This stores the log in memory and will attach the last `n` log lines to the
context of the error.  See [Errors#warn](#errors#warn) to log a warn message.

**Parameters**

**logMessage**: `String`, The message to log.

**Returns**: , undefined

### Errors.wrap(fn)

Wrap a function so that any uncaught errors are caught and reported to the
error aggregator.

**Parameters**

**fn**: `function`, The function to wrap.

**Returns**: `function`

**Example**:
```js
// Wraps function, any errors occurring within the function are caught, logged, and rethrown.
var wrappedFunction = oErrors.wrap(function() {
  throw new Error("My Error");
});

If you want to attach additional contextual information to the error, see
{@link Errors#wrapWithContext}.
 -
```

### Errors.wrapWithContext(context, fn)

Wrap a function so that any uncaught errors are caught and reported to the error
aggregator.
This method allows additional context to be attached to the error if it
occurs.

**Parameters**

**context**: `Object`, Additional context to report along with the error
                                if the function `fn` throws an Error.

**fn**: `function`, The function to wrap

**Returns**: `function`

**Example**:
```js
// Wrap a function with some additional context to be reported in the event
// `doSomethingCallback` throws an error.
setTimeout(oErrors.wrapWithContext({ "context:url": "example.com" }, doSomethingCallback), 1000);
```

### Errors.destroy()

Remove the `oErrors.log` event listener and clean up as much of the Raven
client as possible.

Errors is unusable after a call to destroy and calling `init` subsequently
will fail.

**Returns**: , undefined


* * *
